### References:

* https://numpy.org/devdocs/user/basics.types.html
* https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.intp
* https://numpy.org/devdocs/


## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [3]:
import numpy as np

## Creating numpy array

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

In [7]:
l=[[1,2],[3,4],[5,6]]
#l[0][1]
a=np.array(l)
a.dtype
# print(type(a))

dtype('int64')

In [5]:
t = (10, 20, 30, 40, 50)

# Convert the tuple to a NumPy array
arr = np.array(t)

# Print the array and its type
print(arr)        
print(type(arr))  

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
#print(a)
l=[12,3,4,5]
a=np.array(l)
a

array([12,  3,  4,  5])

In [8]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [11]:
l=[1,2,3,4]
l2=np.array(l)
print(l2)
print(type(l))

[1 2 3 4]
<class 'list'>


In [10]:
ll=np.array(l)
print(type(ll))

<class 'numpy.ndarray'>


In [18]:
# print(h)
h=np.arange(1,11,3)# start stop step
print(h)


[ 1  4  7 10]


The linspace function creates an array of evenly spaced values over a specified range.

The first argument (1) is the starting value of the sequence.
The second argument (20) is the ending value of the sequence.
The third argument (9) is the number of elements you want in the array.

In [25]:
k=np.linspace(1,20,20)   #  gnerate number
print(k)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [22]:
y=np.loadtxt("file.txt")
print(y,type(y))

FileNotFoundError: file.txt not found.

In [28]:
import numpy as np
print(np.empty((3,4)))

#initially there is garbage

[[1.22265147e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 3.40846747e-057 1.47715823e-075 1.60366010e-051]
 [3.73381808e-061 3.43757901e+179 4.50333498e+174 1.32656400e-075]]


In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

# Indexes

In [32]:
a=np.array([1,2,3,4,5,6])
a[a%2!=0]=0      #set odd indexes to zero

# a[2] = 'a'

print(a,type(a),a.dtype)



[0 2 0 4 0 6] <class 'numpy.ndarray'> int64


In [33]:
print(a[0:5:2])

print(a[[1,4,5,2]])#getting first and fourth index

[0 0 0]
[2 0 6 0]


In [35]:
print(a)
print(a[[0,4]])

a[[0,4]] = [2 , 3]

print(a[[0,4]])

print(a)


[2 2 0 4 3 6]
[2 3]
[2 3]
[2 2 0 4 3 6]


In [19]:
## Accessing Rows and Columns

In [40]:
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# col = b[:2,:1] 
# print("cols  = ",col)

row  = b[:,2::-1]
print("data =" , row)


data = [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [41]:
a[a%2!=0]=0
a

array([2, 2, 0, 4, 0, 6])

In [42]:
s=np.array(['a','b','c','b','a'])
s[s!='a']='z'
print(s)

['a' 'z' 'z' 'z' 'a']


# Functions of Numpy

In [45]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, 5, np.nan, 7])

# Check which elements are NaN

# print(nan)

print(np.isnan(arr))  


[False False  True False False  True False]


In [65]:
indx = np.isnan(arr)
print(indx)
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)


[False False  True False False  True False]
[1. 2. 4. 5. 7.]


In [48]:
print("Sum excluding NaNs:", np.nansum(arr))
# print(sum(arr))


Sum excluding NaNs: 19.0


In [52]:
arr_2d = np.array([[1, 2, np.nan], 
                    [4, np.nan, 6], 
                    [7, 8, 9]])

# Compute column-wise mean ignoring NaN
col_mean = np.nanmean(arr_2d, axis=0)

print(col_mean)

# Find indices where NaN exists
inds = np.where(np.isnan(arr_2d))

print(inds)

# Replace NaNs with the mean of the corresponding column
arr_2d[inds] = np.take(col_mean, inds[1])

print(arr_2d)


[4.  5.  7.5]
(array([0, 1]), array([2, 1]))
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [27]:
# a=np.array([1,2,3,10,5,6])
# print(a)

a=np.array([[1,2],[13,4],[5,6]],dtype=np.int8)
print(a)


# a=np.array([[1,2],[13,4],[5,6]],dtype=np.int8)
# print(a)

[[ 1  2]
 [13  4]
 [ 5  6]]


In [28]:
a.shape

(3, 2)

In [29]:
a.ndim

2

In [30]:
a.dtype

dtype('int8')

In [31]:
a.size

6

In [32]:
np.max(a,axis=0)

array([13,  6], dtype=int8)

In [33]:
print(a)
a.argmax()   #returns the index of a flattened array if axis not specified

[[ 1  2]
 [13  4]
 [ 5  6]]


np.int64(2)

In [34]:
a.argmin()

np.int64(0)

In [35]:
a.argsort()


array([[0, 1],
       [1, 0],
       [0, 1]])

In [36]:
b = np.array([1,2,3,5,4,6])

b.argsort()

array([0, 1, 2, 4, 3, 5])

In [37]:
Z=np.zeros(10,np.int8)
Z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [38]:
# print(type(Z))
Z.dtype
Z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [39]:
ZZ=np.zeros((10,10))

In [40]:
print(ZZ)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
ZZZ=np.zeros((10,10,2))

In [42]:
print(ZZZ)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  

In [43]:
ZZZ.ndim

3

In [44]:
O=np.ones(10)

In [45]:
print(O)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [46]:
print(O.dtype)

float64


In [47]:
p=np.arange(99)

In [48]:
print(p, p.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98] int64


In [49]:
k=p.reshape(33,3)
print(k)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]
 [60 61 62]
 [63 64 65]
 [66 67 68]
 [69 70 71]
 [72 73 74]
 [75 76 77]
 [78 79 80]
 [81 82 83]
 [84 85 86]
 [87 88 89]
 [90 91 92]
 [93 94 95]
 [96 97 98]]


In [50]:
print(k.shape)

(33, 3)


In [51]:
k.ndim

2

In [52]:
h=k.ravel()       #flattens the 2D array
print(h)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [53]:
print(h.shape)

(99,)


In [54]:
a=np.array([1,2,3,10,5,6],np.int8)
print(a)

[ 1  2  3 10  5  6]


In [55]:
b=np.arange(9).reshape(3,3)

In [56]:
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
np.sum(b)

np.int64(36)

In [58]:
np.sum(b,axis=0)

array([ 9, 12, 15])

In [59]:
np.sum(b,axis=1)

array([ 3, 12, 21])

In [345]:
a=[3,22,3,44,5,6,1]
a=np.array(a)
k=np.where(a>2,a+10,a+100)
k
# a[a!==0]

array([ 13,  32,  13,  54,  15,  16, 101])

# Arithmatics 

In [347]:
a=np.array([1,2,3,10,5,6],np.int8)
print(a)


[ 1  2  3 10  5  6]


In [348]:
print(a+2)

[ 3  4  5 12  7  8]


In [349]:
print(a-2)

[-1  0  1  8  3  4]


In [350]:
print(a+2,a-2,a*2,a/2,a**2)

[ 3  4  5 12  7  8] [-1  0  1  8  3  4] [ 2  4  6 20 10 12] [0.5 1.  1.5 5.  2.5 3. ] [  1   4   9 100  25  36]


In [351]:
b=np.array([1,2,2,8,7,6],np.int8)
print(a*b)

[ 1  4  6 80 35 36]


In [134]:
print(a==b)

[ True  True False False False  True]


In [352]:
print(a>=b)

[ True  True  True  True False  True]


In [353]:
print(a<=b)

[ True  True False False  True  True]


In [354]:
print(a!=b)

[False False  True  True  True False]


In [355]:
b

array([1, 2, 2, 8, 7, 6], dtype=int8)

In [356]:
b.T

array([1, 2, 2, 8, 7, 6], dtype=int8)

In [357]:
b

array([1, 2, 2, 8, 7, 6], dtype=int8)

In [358]:
l=[1,2,3,4,5]
l

[1, 2, 3, 4, 5]

### NumPy Array Statistical Functions

In [68]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)
print("Mean:",mean_marks)

# compute the median of marks
median_marks = np.median(marks)
print("Median:",median_marks)

# find the minimum and maximum marks
min_marks = np.min(marks)
print("Minimum marks:", min_marks)

max_marks = np.max(marks)
print("Maximum marks:", max_marks)

Mean: 77.2
Median: 78.0
Minimum marks: 66
Maximum marks: 85


### NumPy Array Input/Output Functions
NumPy offers several input/output (I/O) functions for loading and saving data to and from files.

In [360]:
# create an array
array1 = np.array([[1, 3, 5], [2, 4, 6]])

# save the array to a text file
np.savetxt('data.txt', array1)

# load the data from the text file
loaded_data = np.loadtxt('data.txt')

# print the loaded data
print(loaded_data,loaded_data.dtype,array1.dtype)

[[1. 3. 5.]
 [2. 4. 6.]] float64 int64


##### Trigonometric Functions

In [70]:
import numpy as np
import warnings

# Temporarily ignore all warnings
warnings.filterwarnings("ignore")


# array of angles in radians
angles = np.array([0, 1, 2])
print("Angles:", angles)

# compute the sine of the angles
sine_values = np.sin(angles)
print("Sine values:", sine_values)

# compute the inverse sine of the angles
inverse_sine = np.arcsin(angles)
print("Inverse Sine values:", inverse_sine)

Angles: [0 1 2]
Sine values: [0.         0.84147098 0.90929743]
Inverse Sine values: [0.         1.57079633        nan]
